In [2]:
import numpy as np

$$ Promedio = \frac{\sum_{}{x}}{n}$$

In [44]:
def promedio(array):
    sumatoria = 0
    #if isinstance(array, np.ndarray) :
    #    print('Yes it is')
    #    array = array[0]
    #    for i in array:
    #        sumatoria += i
    #else:
    for i in array:
        sumatoria += i
    
    
    return sumatoria/len(array)



$$ Mediana = \frac{n+1}{2}$$

In [35]:
def mediana(array):
    
    if len(array) % 2 == 1:
        print(f'impar {len(array) / 2} long = {len(array)}')
        m = int(len(array) / 2)
        print(m)
        print(array[m])
    else:
        print(f'Par {len(array) / 2} long = {len(array)}')
        m = int(len(array) / 2)
        r = (array[m] + array[m-1]) / 2
        print(r)
    

In [43]:
b = np.arange(0,17)
print(b)
mediana(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
impar 8.5 long = 17
8
8


In [17]:
a = np.arange(0,10)

In [18]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
print(promedio(a))

4.5


In [8]:
r = np.random.randint(0,15, size=(1,10))

In [9]:
r

array([[ 1,  7, 12,  4, 14, 10,  4,  4,  7,  6]])

In [13]:
r[0]

array([ 1,  7, 12,  4, 14, 10,  4,  4,  7,  6])

In [26]:
print(promedio(r))

Yes it is
13.8


In [4]:
l = list(np.arange(0,15))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [7]:
print(promedio(l))

7.0


In [13]:
promedio()

[11 27 19 29 32  7 42  6 28 45]


24.6