In [1]:
import numpy as np 
%reload_ext memory_profiler
#%memit 
import time

In [2]:
#dir(np)

In [3]:
list_a = [1,2,3,4,5,6]
list_b = [1,2,3,4,5,6]
list_a

[1, 2, 3, 4, 5, 6]

In [4]:
list_a + list_b

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [5]:
# 1D Array

a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
# 2D Array

b = np.array([(1,2,3),(4,5,6)])
print(b) 

[[1 2 3]
 [4 5 6]]


In [7]:
import sys 

In [8]:
s = range(1000)
print(f'Memory: {(sys.getsizeof(5) * len(s)) / 1024} KBs')

Memory: 27.34375 KBs


In [9]:
s1 = np.arange(1000)
print(f'Memory: {(s1.size*s1.itemsize) / 1024} KBs')

Memory: 3.90625 KBs


In [ ]:
# test

size = 1000000
List_1 = range(size)
List_2 = range(size)
Array_1 = np.arange(size)
Array_2 = np.arange(size)

start = time.time()

result = [(x,y) for x,y in zip(List_1, List_2)]
print(f'{(time.time() - start)*1000} ms')

In [ ]:
%%time

aux = []

for i in range(0,len(List_1)):
    aux.append(List_1[i] + List_2[i])


#aux

In [ ]:
#result

In [ ]:
start = time.time()
result = Array_1 + Array_2
print(f'{(time.time() - start)*1000} ms')

In [ ]:
result

In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
arr

In [ ]:
only_ones = np.ones((3,4))
only_ones

In [ ]:
only_ones2 = np.ones((5,5))
only_ones2

In [ ]:
only_ones2 = np.ones((10000,10000))
only_ones2
print(f'Memory: {((only_ones2.size*only_ones2.itemsize) / 1024)/ 1024} MBs')

In [ ]:
only_zeros = np.zeros((3,4))
only_zeros

In [ ]:
only_zeros2 = np.zeros((5,5))
only_zeros2

In [ ]:
ran = np.random.random((5,5))
ran

In [ ]:
emp = np.empty((5,5)) # Takes cache memory 
emp

In [ ]:
full = np.full((4,4), 5) # Matrix of a specific number
full

In [ ]:
space = np.arange(0,30,5) # From 0 to 30 by steps of 5
space2 = np.arange(0,20,5)
space3 = np.arange(0,40,7)
space

In [ ]:
space = np.array([np.arange(0,10,1),np.arange(0,10,1),np.arange(0,10,1)])
space 

In [ ]:
space = np.linspace(0,30,10)
space

In [ ]:
ind = np.eye(10,10)
ind

In [ ]:
ind2 = np.identity(10)
ind2

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.ndim # 1D 2D or 3D Matrix

In [ ]:
a.dtype

In [ ]:
a.size # Amount of elements

In [ ]:
a.shape # Matrix Shape

In [ ]:
a = np.array([[1,2,3],[4,5,6]]) # Matrix of 2x3
print(a)
a = a.reshape(3,2) # Reshape 3x2
print(a)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Matrix of 3x3
print(a)
a = a.reshape(1,9) # Reshape 1x9
print(a)

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]) # Matrix of 4x4
print(a)
a = a.reshape(2,8) # Reshape 2x8
print(a)
a = a.reshape(8,2) # Reshape 2x8
print(a)

In [ ]:
a[2,1]

In [ ]:
a[0:, 0]

In [ ]:
a.min() # Min value

In [ ]:
a.max() # Max value

In [ ]:
a.sum() # Sum of all values

In [ ]:
np.sqrt(a)

In [ ]:
np.std(a) # Standard Deviation 

In [ ]:
np.prod(a) # Product of the matrix => n1 * n2 * n3 * ... nn

In [ ]:
np.mean(a) # Mean of the matrix

In [ ]:
np.var(a) # Variance of the matrix

In [ ]:
np.argmin(a) # Return index of the min value

In [ ]:
np.argmax(a) # Return index of the max value

In [ ]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,2,3],[4,5,6]])
print(X+Y)
print(X-Y)
print(X*Y)
print(X/Y)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

In [ ]:
a + 20

In [ ]:
X = np.array([1,2,3,4,5])
Y = np.array([1,2,3,4,5])
X @ Y 

In [ ]:
%%time
z = np.random.random(1000000)
#Z = np.array([2,545,45,65,3,7,8,51,5,436])
np.sort(z)

In [ ]:
%%time
a = np.array([np.random.random(5),np.random.random(5),np.random.random(5),np.random.random(5),np.random.random(5)]) 
print("----------------")
print(f'Memory: {(a.size*a.itemsize) / 1024} KBs')
print(a)
a = a.reshape(1,25) 
print("----------------")
print(f'Memory: {(a.size*a.itemsize) / 1024} KBs')
print(a)
a = np.sort(a)
print("----------------")
print(f'Memory: {(a.size*a.itemsize) / 1024} KBs')
print(a)
a = a.reshape(5,5) 
print("----------------")
print(f'Memory: {(a.size*a.itemsize) / 1024} KBs')
print(a)


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
5 > a

In [ ]:
5 < a 

In [ ]:
from skimage import io 

In [ ]:
photo = io.imread('dogormuffin.jpg')
type(photo)

In [ ]:
photo.shape

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.imshow(photo)

In [ ]:
plt.imshow(photo[::-1])

In [ ]:
plt.imshow(photo[:, ::-1])

In [ ]:
plt.imshow(photo[0:534, 0:480])

In [ ]:
plt.imshow(photo[::2, ::2])
print(photo[::2, ::2].shape)

In [ ]:
photo_sin = np.sin(photo) 
photo_sin

In [ ]:
photo_msk = np.where(photo > 100, 255, 0)

In [ ]:
plt.imshow(photo_msk)

In [ ]:
plt.imshow(photo[:,:,0].T)

In [ ]:
data = np.genfromtxt('data.txt', dtype=None, delimiter=',')
data

# Part 2

In [3]:
L = np.random.rand(4,4) # Random Decimals
L

array([[0.30234453, 0.70392529, 0.39202331, 0.24103435],
       [0.41665232, 0.27525922, 0.79669715, 0.63299566],
       [0.57051446, 0.19045709, 0.71633398, 0.44642804],
       [0.55864003, 0.97943145, 0.22887162, 0.25115393]])

In [6]:
L2 = np.random.randint(21,30, size=(5,5)) # Random Integer
L2

array([[29, 23, 25, 25, 25],
       [21, 27, 24, 23, 25],
       [27, 29, 26, 28, 21],
       [27, 27, 27, 25, 26],
       [23, 23, 27, 29, 25]])

In [19]:
L3 = np.random.randint(21,50,size=(10,10))
#L3

In [21]:
len(L3[L3 <= 30])

45

In [22]:
L4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
L4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
L4[1:3,0:2]

array([[ 5,  6],
       [ 9, 10]])

In [44]:
L4[[0,1,2,3],[0,1,2,3]]

array([ 1,  6, 11, 16])

In [45]:
L4[[0,1,2],[1,2,3]]

array([ 2,  7, 12])

In [46]:
L4[[0,2,3],2:]

array([[ 3,  4],
       [11, 12],
       [15, 16]])

In [56]:
A = np.array([[1,2,3,4,5]]) # Horizontal
#A
R = np.repeat(A,5,axis=0)
R

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [54]:
A = np.array([[1],[2],[3],[4],[5]]) # Vertical
#A
R = np.repeat(A,5,axis=1)
R

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [57]:
list_1 = np.array([1,2,3,4,5,6,7,8,9])

In [58]:
np.log(list_1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [59]:
np.exp(list_1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [60]:
M = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
M

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
MT = M.T # Transpose
MT

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [62]:
MT.sum(axis=1) # Sum Horizontal

matrix([[12],
        [15],
        [18]])

In [63]:
MT.sum(axis=0) # Sum Vertical

matrix([[ 6, 15, 24]])

In [66]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [76]:
Z = np.zeros((3,3))
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
O = np.ones((3,3))
O

array([[1., 1., 1.]])

In [75]:
ZO = np.vstack((Z,O))
ZO

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.]])

In [70]:
OZ = np.vstack((O,Z))
OZ

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
ZO2 = np.hstack((Z,O))
ZO2

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [72]:
OZ2 = np.hstack((O,Z))
OZ2

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [77]:
M2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
M2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [87]:
MSV, MSV2, MSV3 = np.vsplit(M2,3)
print(MSV)
print(MSV2)
print(MSV3)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [83]:
MSH, MSH2, MSH3 = np.hsplit(M2,3)
print(MSH)
print(MSH2)
print(MSH3)

[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [93]:
N = np.array([[1,2,3],[4,5,6],[7,8,9]])
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
N[2,:] = [0,0,0]
N

array([[0, 0, 0],
       [0, 5, 0],
       [0, 0, 0]])

In [98]:
# 3D Matrix

M3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
M3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
M3D[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
M3D[0,0]

array([1, 2, 3])

In [101]:
M3D[0,0,0]

1

In [104]:
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 5 0 1
# 1 0 0 0 1
# 1 1 1 1 1

ones = np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [106]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [108]:
zeros[1,1] = 5
zeros

array([[0., 0., 0.],
       [0., 5., 0.],
       [0., 0., 0.]])

In [112]:
ones[1:4,1:4] = zeros
ones

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 5., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [113]:
# 1 2 3
# 8 9 4
# 7 6 5

z = np.ones((3,3))
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [134]:
z[0, :] = [1,2,3]
z


array([[1., 2., 3.],
       [8., 9., 2.],
       [6., 5., 4.]])

In [135]:
z[1:,2] = [4,5]
z

array([[1., 2., 3.],
       [8., 9., 4.],
       [6., 5., 5.]])

In [136]:
z[2,1::-1] = [6,7]
z

array([[1., 2., 3.],
       [8., 9., 4.],
       [7., 6., 5.]])

In [137]:
z[1,:2] = [8,9]
z

array([[1., 2., 3.],
       [8., 9., 4.],
       [7., 6., 5.]])